config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
    render :index
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_url
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if article.errors %>
  <ul>
    <% article.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<% @articles.each do |article| %>
<article>
  <%= link_to article.title, article %>
  <p><%= article.body %></p>
  <p>Created at: <%= article.created_at.to_date %></p>
</article>
<% end %>
<%= link_to "Create New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<% if @article.errors %>
  <ul>
    <% @article.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<p>Created at: <%= @article.created_at.to_date %></p>
<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Delete",
article_path(@article), data: {turbo_method: :delete, turbo_confirm: "are you
sure??"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>